### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by davidrock** [zakariaGatter/MarkGate#1]
When I tried to run `source /path/to/markgate/markgate.sh`
I received this error message:

![image](https://user-images.githubusercontent.com/19226926/71821509-15004b80-3071-11ea-817e-13b01913cfdf.png)

I am using MacOS Catalina.

**Comment by zakariaGatter** [comment]
Ok I'll check it out

**Comment by zakariaGatter** [comment]
I never try it on MacOs but on Linux it work fine 
Did have a alias with the same name as ga ?!

**Comment by davidrock** [comment]
Oh yes, you're right.

https://github.com/ohmyzsh/ohmyzsh/wiki/Cheatsheet#git

As you can see, 'ga' is an alias for 'git add' command.

**Comment by zakariaGatter** [comment]
So the solution is to change the 'git add' alias or to change the functions names in markgate.zsh file
